version: '3.7'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /casterlyrock/mongo_data:/data/db

  mlflow:
    build: ./mlflow
    ports:
      - "5000:5000"
    volumes:
      - /casterlyrock/mlruns:/mlruns
    links:
      - mongodb

  webserver:
    build:
      context: ./webserver
      dockerfile: Dockerfile_laptop
    ports:
      - "3000:3000"
      - "3001:3001"
    links:
      - mlflow
      - mongodb
    volumes:
      - /casterlyrock:/casterlyrock
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:/casterlyrock
